Notes:

- Catalogue generation starts:98(not sure about this)  ends: 396

- Added a TON of int() calls to fix numpy. This might not be the best way?

- Getting this error when generating initial table:

Traceback (most recent call last):
  File "tetra.py", line 769, in <module>
    tetra(image_file_name)
  File "tetra.py", line 690, in tetra
    num_nearby_catalog_stars = len(get_nearby_stars_compressed_course(image_center_vector, fov_half_diagonal_rad))
  File "tetra.py", line 133, in get_nearby_stars_compressed_course
    indices = compressed_course_sky_map[index:index+2]
TypeError: slice indices must be integers or None or have an __index__ method

	However, the table still seems to generate fine and work after? Investigate later.

